version: '3'

services:
  web:
    image: discoreg
    build:
      context: ./discoreg
      dockerfile: Dockerfile
    container_name: discoreg
    ports: 
      - '80:80'
    env_file:
      - example.env
  worker:
    image: nextupbot
    build:
      context: ./discoreg
      dockerfile: Dockerfile.nextupbot 
    container_name: nextupbot
    env_file:
      - example.env
