FROM python:3.8

ENV PYTHONUNBUFFERED 1

WORKDIR /discoreg

COPY requirements.txt /discoreg
RUN pip3 install -r requirements.txt --no-cache-dir
COPY . /discoreg

ENTRYPOINT ["python3"]
CMD ["discoreg/manage.py", "nextupbot"]
